### PR TITLE
fix #23 missing method in HashTiming (RandomLib 1.2)

### LINKED ISSUE #23: 2.7: issue with latest RandomLib
With RandomLib (and without mcrypt), running zend-form test suite:

`PHP Fatal error:  Class Zend\Math\Source\HashTiming contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (RandomLib\Source::isSupported) in /usr/share/php/Zend/Math/Source/HashTiming.php on line 111
`

### PR DESCRIPTION
**Pull request by remicollet**

### CODE REVIEW

**Comment by remicollet** [comment]
@ircmaxell can you please have a look, I think the new method in RandomLib\Source interface  (v1.2.0) is a BC break.

**Comment by ircmaxell** [comment]
Yes, it was a bc break for people extending the interface (hence the bump to 1.2). For users of the system it wasn't (hence not bumping to 2.0).

**Comment by mchastainfm** [comment]
So I need the changes fixed by this PR...At this point I guess I will fork and do the composer work on my end to keep my app from crashing until somebody addresses this.  Is there any reason it hasnt been resolved or am I missing something and it already has been?

**Comment by weierophinney** [comment]
`legacy` was pre-2.5, and was a split off of the monolithic repository; we kept it only for purposes of maintaining commit references to prevent breakage of `composer.lock` references.

When I rebased this one to the release-2.7 branch (based off of the 2.7.0 release), it demonstrates that the fix is already present.

**Pull request closed without merging**
