### PR TITLE
tidy up readme

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by GeeH** [comment]
Changes of this nature are more time consuming to merge than the value they provide. Please refrain from submitting PR that only modify whitespace or make minor grammatical changes.

Thanks!

**Comment by samsonasik** [comment]
well, there are some PR that I want to provide, but currently stopped as no "develop" branch, ( for ex : remove deprecated classes/methods as previously closed by @Maks3w  as we don't decide a major change right now). What I can do is something like this for now. btw, thanks for merging

**Comment by GeeH** [comment]
Your merge takes longer to merge than the value it provides, I don't mean to seem ungreatful but I'll be just closing these kind of PR in future.

**Comment by GeeH** [comment]
I apologise @samsonasik - this made a valid change that makes the README render better, ignore me, I've had a bad day.

**Pull request merged**
